global:
  resolve_timeout: 1m
  slack_api_url: "https://hooks.slack.com/services/{api_has}"
route:
  group_by: ['instance']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 20s
  receiver: slack

receivers:
  - name: slack
    slack_configs:
      - channel: "#webhook-channel"
        text: "summary: {{ .CommonAnnotations.summary }} \ndescription: {{ .CommonAnnotations.description }}"