global:
  scrape_interval: 5s
  evaluation_interval: 15s

  external_labels:
    monitor: 'demo-monitor'

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "demo"
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['demo1:8080', 'demo2:8080']